import { Container } from './components/Container';
import { Footer } from './components/Footer';
import { Header } from './components/Header';
import { Providers } from './components/Providers';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container>
            <Header />
            <main>{children}</main>
            <Footer />
          </Container>
        </Providers>
      </body>
    </html>
  );
}
